export {
	ADAPTIVE_CONCRETE_LEVELS,
	ADAPTIVE_FALLBACK,
	type AdaptiveConcreteLevel,
	clampAdaptiveToAvailable,
	classifyAdaptiveReasoning,
	heuristicAdaptiveEffort,
	parseAdaptiveEffort,
} from "./adaptive-reasoning.ts";
export {
	ACTIVITY_DOT_FRAMES,
	ANIMATIONS,
	type AnimationId,
	type AnimationLoaderOptions,
	type AnimationSpec,
	activityIndicatorOptions,
	animationLoaderOptions,
	buildActivityFrames,
	DEFAULT_ANIMATION_ID,
	EASTER_EGG_CHANCE,
	easterEggsFor,
	formatActivityLine,
	formatAnimationMessage,
	getAnimation,
	getPorcupineActivity,
	isAnimationId,
	isEasterEggAnimation,
	isToolDrivenAnimation,
	normalizeActivityPhase,
	normalizeAnimationId,
	PORCUPINE_ACTIVITIES,
	type PorcupineActivityPhase,
	pickStatusAnimation,
	resolveActivityFromText,
	resolveActivityFromToolName,
	resolveAnimationFromText,
	resolveAnimationFromToolName,
	resolveToolActivity,
	skillNameFromPath,
	type ToolActivity,
} from "./animations.ts";
export {
	AUTO_MODE_AUTONOMY_DIRECTIVE,
	type AutoVerdict,
	type BashGuardDecision,
	type BashGuardMode,
	classifyAutoModeCommand,
	type DangerousMatch,
	detectDangerousCommand,
	disableSessionAuto,
	enableSessionAuto,
	guardBashCommand,
	isSessionAutoEnabled,
	toggleSessionAuto,
} from "./auto-mode.ts";
export {
	createAutonomousCapabilityLearner,
	createAutonomousCapabilityLearningAdapters,
} from "./capability-learning.ts";
export {
	formatGuideCommandOutput,
	type GuideTopic,
	getGuideTopics,
} from "./guide.ts";
export {
	applyLearningProposal,
	buildLearningGraph,
	formatLearningStatus,
	type LearningGraph,
	type LearningOutcome,
	type LearningProposal,
	type LearningProposalKind,
	type LearningProposalStatus,
	type LearningToolEvidence,
	listLearningProposals,
	type PostTurnLearningObservation,
	type PostTurnLearningOptions,
	processPostTurnLearning,
	rejectLearningProposal,
} from "./learning-store.ts";
export { classifyWithSessionModel } from "./llm-classify.ts";
export {
	ensureMemoryFiles,
	extractUserPatternsHeuristic,
	formatMemoryForPrompt,
	MEMORY_FILE,
	type MemoryAction,
	type MemoryTarget,
	mutateMemory,
	readMemoryFile,
	USER_FILE,
} from "./memory-store.ts";
export {
	buildPersonalityReminder,
	isTrivialChatTurn,
	PORCUPINE_PERSONALITY_GUIDELINES,
	userRequestedPlanning,
} from "./personality.ts";
export { createHeuristicRuntimeAdapters } from "./session-adapters.ts";
export type { CatalogSkill, CatalogTool } from "./session-bridge.ts";
export {
	artifactChangeFromToolCall,
	buildCapabilityTreeFromSession,
} from "./session-bridge.ts";
export {
	augmentPromptWithPlan,
	formatPlanContextBlock,
	PorcupineSessionOrchestrator,
	type PrepareTurnResult,
	summarizePlan,
	type TaskGraphStepStatus,
	type TaskGraphStepView,
	type TaskGraphView,
} from "./session-orchestrator.ts";
export {
	classifySkillStack,
	describeSkillCapability,
	describeToolCapability,
	formatCapabilityProjection,
	formatStacksCommandOutput,
	formatStacksCompact,
	formatStacksOverview,
	getStack,
	inferStackFromSkillPath,
	isKnownStackId,
	listStacks,
	PORCUPINE_STACKS,
	resolveToolPlacement,
	type SkillStackHint,
	type StackDefinition,
	searchStacks,
	skillCapabilityPath,
	TOOL_STACK_MAP,
	type ToolStackPlacement,
	toolCapabilityPath,
} from "./stacks.ts";
export {
	DEFAULT_SUBAGENT_SESSION_RETENTION,
	listSubagentSessions,
	MAX_SUBAGENT_TRANSCRIPT_BYTES,
	type PersistedSubagentSession,
	type PersistSubagentSessionOptions,
	persistSubagentSession,
	pruneSubagentSessions,
	type SubagentSessionResult,
	type SubagentSessionSummary,
} from "./subagent-sessions.ts";
